quality <- read.csv('D:/AryanPra/quality.csv')
str(quality) 
table(quality$PoorCare) 
library(caTools) 
set.seed(88) 
split = sample.split(quality$PoorCare, SplitRatio = 0.75) 
split 
qualityTrain = subset(quality, split == TRUE) 
qualityTest = subset(quality, split == FALSE) 
nrow(qualityTrain) 
nrow(qualityTest) 
QualityLog = glm(PoorCare ~ OfficeVisits + Narcotics,data=qualityTrain, family=binomial)
summary(QualityLog)  
predictTrain = predict(QualityLog, type="response") 
summary(predictTrain) 
 tapply(predictTrain, qualityTrain$PoorCare, mean) 